// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "match_server/Match.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include <queue>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <ctime>
#include <cstdlib>
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::match_server;
using namespace std;

struct Task{
    string opt;
    User user;
    string output_file;
    int num;
};

struct MessageQueue{
    queue<Task>q;
    mutex m;
    condition_variable cv;
}message_queue;

//bool cmp1(vector<User>)
bool cmp1(const User& a,const User& b)
{
    if(a.id!=b.id)
        return a.name<b.name;
    return a.id<b.id;
}
class Pool{
    public:
        void list(const string& output_file)
        {
            ofstream out;
            out.open("..//..//result//"+output_file);
            sort(users.begin(),users.end(),cmp1); 
            for(vector<User>::iterator it=users.begin();it!=users.end();it++)
                out<<it->id<<' '<<it->name<<endl;
            out<<"total num: "<<users.size()<<endl;
            return ;
        }
        void get_rand(const string& output_file,const int& num)
        {
            ofstream out;
            out.open("..//..//result//"+output_file);
            sort(users.begin(),users.end(),cmp1);
            int tot=num;
            while(tot--&&users.size())
            {
                int pos=rand()%users.size();
                out<<users[pos].id<<' '<<users[pos].name<<endl;
                users.erase(users.begin()+pos);
            }
            return ;
        }
        void add(const User& user)
        {
            users.push_back(user);
            return ;
        }
        void remove(const User& user)
        {
            for(uint32_t i=0;i<users.size();i++)
                if(users[i].id==user.id)
                {
                    users.erase(users.begin()+i);
                    break;
                }
            return ;
        }
    private:
        vector<User> users;
}pool;






class MatchHandler : virtual public MatchIf {
    public:
        MatchHandler() {
            // Your initialization goes here
        }

        int32_t add_user(const User& user, const std::string& info) {
            // Your implementation goes here

            unique_lock<mutex> lck(message_queue.m);
            message_queue.q.push({"add",user,"",0});
            message_queue.cv.notify_all();
            printf("add_user\n");
            return 0;
        }

        int32_t remove_user(const User& user, const std::string& info) {
            // Your implementation goes here
            unique_lock<mutex> lck(message_queue.m);
            message_queue.q.push({"remove",user,"",0});
            message_queue.cv.notify_all();
            printf("remove_user\n");
            return 0;
        }

        int32_t list_user(const std::string& output_file, const std::string& info) {
            // Your implementation goes here
            unique_lock<mutex> lck(message_queue.m);
            message_queue.q.push({"list",User(),output_file,0});
            message_queue.cv.notify_all();

            printf("list_user\n");
            return 0;
        }

        int32_t get_random(const int32_t num, const std::string& output_file, const std::string& info) {
            // Your implementation goes here
            unique_lock<mutex> lck(message_queue.m);
            message_queue.q.push({"rand",User(),output_file,num});
            message_queue.cv.notify_all();
            printf("get_random\n");
            return 0;
        }

};

void consume_task()
{
    while(true)
    {
        unique_lock<mutex> lck(message_queue.m);
        if(message_queue.q.empty())
        {
            message_queue.cv.wait(lck);
        }
        else
        {
            auto task=message_queue.q.front();
            message_queue.q.pop();
            lck.unlock();
            if(task.opt=="add")
                pool.add(task.user);
            else if(task.opt=="remove")
                pool.remove(task.user);
            else if(task.opt=="list")
                pool.list(task.output_file);
            else if(task.opt=="rand")
                pool.get_rand(task.output_file,task.num);
        }
    }
    return ;
}

int main(int argc, char **argv) {
    int port = 9090;
    ::std::shared_ptr<MatchHandler> handler(new MatchHandler());
    ::std::shared_ptr<TProcessor> processor(new MatchProcessor(handler));
    ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);

    cout<<"Match_server"<<endl;
    srand(time(0));
    thread matching_thread(consume_task);
    server.serve();
    return 0;
}

